services:
  fluent-bit:
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
    container_name: project-logs
    environment:
      AWS_PROFILE: default         # dosyadan alacak
    volumes:
      - logs-data:/logs:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./aws-cred:/root/.aws:ro   # <— kimlik dosyaları burada
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    restart: unless-stopped

  app:
    build:
      context: "C:/Users/foyko/Desktop/furkan.yildiz/Project"
      dockerfile: "C:/Users/foyko/Desktop/furkan.yildiz/Project/Dockerfile"
    container_name: project-app
    ports:
      - "8081:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - logs-data:/logs
    depends_on:
      - fluent-bit
    restart: unless-stopped

volumes:
  logs-data: {}
